import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Store } from "lucide-react";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";
export const Route = createFileRoute("/employer/stores")({ component: () => <RoleGuard role="employer"><Stores /></RoleGuard> });
function Stores(){const {user}=useAuth();const qc=useQueryClient();const [name,setName]=useState("");const [category,setCategory]=useState("");const [address,setAddress]=useState("");const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);const {data=[],isLoading}=useQuery({queryKey:["employer-stores",user?.id],enabled:!!user?.id,queryFn:async()=>{const {data,error}=await supabase.from("stores" as any).select("*").eq("employer_id",user!.id).order("created_at",{ascending:false});if(error)throw error;return data??[]}});const save=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!user)return;setSaving(true);setMessage("");const {error}=await supabase.from("stores" as any).insert({employer_id:user.id,store_name:name.trim(),category:category||null,address:address||null});setSaving(false);if(error){setMessage(error.code==="23503"?"ไม่พบ Employer Profile ของบัญชีนี้ กรุณาสร้าง Employer Profile ก่อน":"บันทึกร้านไม่สำเร็จ: "+error.message);return}setName("");setCategory("");setAddress("");setMessage("บันทึกร้านเรียบร้อยแล้ว");await qc.invalidateQueries({queryKey:["employer-stores",user.id]});await qc.invalidateQueries({queryKey:["employer-dashboard",user.id]})};return <div className="mx-auto max-w-4xl space-y-6"><header><h1 className="font-display text-4xl font-bold">ร้านของฉัน</h1><p className="mt-1 text-sm text-muted-foreground">เพิ่มสถานประกอบการก่อนสร้างประกาศงาน</p></header><form onSubmit={save} className="grid gap-3 rounded-xl border border-border bg-card p-5 sm:grid-cols-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="ชื่อร้าน *" className="rounded border border-input bg-background p-2.5"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="ประเภทร้าน" className="rounded border border-input bg-background p-2.5"/><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="ที่อยู่" className="rounded border border-input bg-background p-2.5"/>{message&&<p className={`text-sm sm:col-span-3 ${message.startsWith("บันทึก")?"text-emerald-600":"text-destructive"}`}>{message}</p>}<button disabled={saving} className="rounded bg-primary px-4 py-2 font-bold text-primary-foreground disabled:opacity-60 sm:col-span-3">{saving?"กำลังบันทึก…":"บันทึกร้าน"}</button></form>{isLoading?<p>กำลังโหลด…</p>:data.length?<div className="space-y-2">{data.map((s:any)=><div key={s.id} className="rounded-xl border border-border bg-card p-4"><div className="flex gap-3"><Store className="h-5 w-5 text-primary"/><div><b>{s.store_name}</b><p className="text-xs text-muted-foreground">{[s.category,s.address].filter(Boolean).join(" · ")||"ยังไม่มีรายละเอียด"}</p></div></div></div>)}</div>:<div className="rounded-xl border border-dashed border-border p-10 text-center text-muted-foreground">ยังไม่มีร้าน</div>}</div>}
