import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, CircleDollarSign, WalletCards } from "lucide-react";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";
import { budgetSpent, financeSummary, monthBounds, thb, type Budget, type Transaction } from "@/lib/finance";

export const Route = createFileRoute("/student/money")({ component: () => <RoleGuard role="student"><MoneyPage /></RoleGuard> });
function MoneyPage() {
  const { user } = useAuth(); const now = new Date(); const bounds = monthBounds();
  const { data = { transactions: [] as Transaction[], budgets: [] as Budget[] }, isLoading } = useQuery({ queryKey: ["money", user?.id, bounds.start], enabled: !!user?.id, queryFn: async () => { const [{ data: transactions, error }, { data: budgets }] = await Promise.all([supabase.from("transactions" as any).select("*").eq("student_id", user!.id).gte("transaction_date", bounds.start).lt("transaction_date", bounds.end).order("transaction_date", { ascending: false }), supabase.from("budgets" as any).select("*").eq("student_id", user!.id).eq("month", now.getMonth()+1).eq("year", now.getFullYear())]); if (error) throw error; return { transactions: (transactions ?? []) as Transaction[], budgets: (budgets ?? []) as Budget[] }; } });
  const summary = financeSummary(data.transactions);
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-display text-4xl font-bold">Money</h1><p className="mt-1 text-sm text-muted-foreground">ภาพรวมการเงินเดือนนี้จากข้อมูลจริงของคุณ</p></div><Link to="/student/transactions" className="rounded-md bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">จัดการรายการเงิน</Link></header>{isLoading ? <div className="h-48 animate-pulse rounded-xl bg-muted" /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={WalletCards} label="เงินคงเหลือเดือนนี้" value={thb(summary.balance)} tone="bg-primary text-primary-foreground" /><Stat icon={ArrowUpRight} label="รายรับเดือนนี้" value={thb(summary.income)} /><Stat icon={ArrowDownRight} label="รายจ่ายเดือนนี้" value={thb(summary.expense)} /><Stat icon={BriefcaseBusiness} label="รายได้ Part-time" value={thb(summary.partTime)} /></section><section className="grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold">รายการล่าสุด</h2><Link to="/student/transactions" className="text-xs font-bold text-primary">ดูทั้งหมด</Link></div>{data.transactions.length ? <div className="mt-3 space-y-2">{data.transactions.slice(0,6).map(t => <div key={t.id} className="flex items-center justify-between rounded-lg bg-muted/50 p-3"><div><div className="font-semibold">{t.category}</div><div className="text-xs text-muted-foreground">{t.description || t.transaction_date}</div></div><b className={t.type === "income" ? "text-emerald-600" : "text-rose-600"}>{t.type === "income" ? "+" : "-"}{thb(Number(t.amount))}</b></div>)}</div> : <Empty text="ยังไม่มีรายการเงิน" />}</div><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold">Budget เดือนนี้</h2><Link to="/student/budgets" className="text-xs font-bold text-primary">จัดการ Budget</Link></div>{data.budgets.length ? <div className="mt-3 space-y-3">{data.budgets.map(b => { const spent = budgetSpent(data.transactions,b.category); const pct = Math.min(100, spent / Number(b.amount) * 100); return <div key={b.id}><div className="flex justify-between text-sm"><span>{b.category}</span><span>{thb(spent)} / {thb(Number(b.amount))}</span></div><div className="mt-1 h-2 rounded-full bg-muted"><div className={`h-full rounded-full ${pct >= 100 ? "bg-destructive" : pct >= 70 ? "bg-amber-500" : "bg-primary"}`} style={{width:`${pct}%`}} /></div></div>})}</div> : <Empty text="ยังไม่ได้ตั้ง Budget เดือนนี้" />}</div></section></>}</div>;
}
function Stat({icon:Icon,label,value,tone="bg-card"}:{icon:any;label:string;value:string;tone?:string}) { return <div className={`rounded-xl border border-border p-5 ${tone}`}><Icon className="h-5 w-5 opacity-70"/><div className="mt-3 text-xs opacity-70">{label}</div><div className="mt-1 font-display text-2xl font-bold">{value}</div></div>; }
function Empty({text}:{text:string}) { return <p className="mt-8 text-center text-sm text-muted-foreground">{text}</p>; }
