import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Plus } from "lucide-react";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";
import { EXPENSE_CATEGORIES, budgetSpent, monthBounds, thb, type Budget, type Transaction } from "@/lib/finance";
export const Route = createFileRoute("/student/budgets")({ component: () => <RoleGuard role="student"><BudgetsPage/></RoleGuard> });
function BudgetsPage(){const {user}=useAuth();const qc=useQueryClient();const now=new Date();const [category,setCategory]=useState("Food"),[amount,setAmount]=useState("");const bounds=monthBounds();const {data={b:[] as Budget[],t:[] as Transaction[]}}=useQuery({queryKey:["budgets",user?.id,now.getMonth()],enabled:!!user?.id,queryFn:async()=>{const [{data:b},{data:t}]=await Promise.all([supabase.from("budgets" as any).select("*").eq("student_id",user!.id).eq("month",now.getMonth()+1).eq("year",now.getFullYear()),supabase.from("transactions" as any).select("*").eq("student_id",user!.id).eq("type","expense").gte("transaction_date",bounds.start).lt("transaction_date",bounds.end)]);return{b:(b??[])as Budget[],t:(t??[])as Transaction[]}}});const save=async(e:React.FormEvent)=>{e.preventDefault();if(Number(amount)<=0)return;await supabase.from("budgets" as any).upsert({student_id:user!.id,category,amount:Number(amount),month:now.getMonth()+1,year:now.getFullYear()},{onConflict:"student_id,category,month,year"});setAmount("");qc.invalidateQueries({queryKey:["budgets",user?.id]});qc.invalidateQueries({queryKey:["money",user?.id]})};return <div className="mx-auto max-w-4xl space-y-6"><header><h1 className="font-display text-4xl font-bold">Budget</h1><p className="mt-1 text-sm text-muted-foreground">กำหนดงบรายเดือนและติดตามการใช้จ่าย</p></header><form onSubmit={save} className="flex flex-wrap gap-2 rounded-xl border border-border bg-card p-4"><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded border p-2">{EXPENSE_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" placeholder="งบประมาณ" className="rounded border p-2"/><button className="inline-flex items-center gap-1 rounded bg-primary px-3 py-2 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4"/>บันทึก Budget</button></form><div className="space-y-3">{data.b.length?data.b.map(b=>{const spent=budgetSpent(data.t,b.category);const raw=spent/Number(b.amount)*100;const pct=Math.min(raw,100);return <div key={b.id} className="rounded-xl border border-border bg-card p-5"><div className="flex justify-between gap-3"><b>{b.category}</b><span>{thb(spent)} / {thb(Number(b.amount))} · {Math.round(raw)}%</span></div><div className="mt-3 h-3 rounded-full bg-muted"><div className={`h-full rounded-full ${raw>100?"bg-destructive":raw>=70?"bg-amber-500":"bg-primary"}`} style={{width:`${pct}%`}}/></div><p className="mt-2 text-xs text-muted-foreground">{raw>100?"เกินงบประมาณ":raw>=90?"ใกล้ถึงขีดจำกัด":raw>=70?"ควรระวังการใช้จ่าย":"อยู่ในงบประมาณ"}</p></div>}):<div className="rounded-xl border border-dashed border-border p-10 text-center text-muted-foreground">ยังไม่มี Budget เดือนนี้</div>}</div></div>}
