import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { RoleGuard } from "@/components/auth/RoleGuard";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES, thb, type Transaction } from "@/lib/finance";

export const Route = createFileRoute("/student/transactions")({ component: () => <RoleGuard role="student"><TransactionsPage /></RoleGuard> });
function TransactionsPage() { const { user } = useAuth(); const qc = useQueryClient(); const [type,setType] = useState("all"); const [open,setOpen] = useState(false); const {data=[],isLoading}=useQuery({queryKey:["transactions",user?.id],enabled:!!user?.id,queryFn:async()=>{const {data,error}=await supabase.from("transactions" as any).select("*").eq("student_id",user!.id).order("transaction_date",{ascending:false});if(error)throw error;return data as Transaction[]}}); const shown=useMemo(()=>type==="all"?data:data.filter(x=>x.type===type),[data,type]); const remove=async(id:string)=>{await supabase.from("transactions" as any).delete().eq("id",id).eq("student_id",user!.id);qc.invalidateQueries({queryKey:["transactions",user?.id]});qc.invalidateQueries({queryKey:["money",user?.id]})}; return <div className="mx-auto max-w-4xl space-y-5"><header className="flex items-center justify-between"><div><h1 className="font-display text-4xl font-bold">Transactions</h1><p className="mt-1 text-sm text-muted-foreground">รายรับและรายจ่ายของคุณ</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4"/>เพิ่มรายการ</button></header><div className="flex gap-2">{["all","income","expense"].map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-full px-3 py-1.5 text-sm ${type===x?"bg-primary text-primary-foreground":"bg-muted"}`}>{x==="all"?"ทั้งหมด":x==="income"?"รายรับ":"รายจ่าย"}</button>)}</div>{isLoading?<p>กำลังโหลด…</p>:shown.length?<div className="overflow-hidden rounded-xl border border-border bg-card">{shown.map(t=><div key={t.id} className="flex items-center justify-between border-b border-border p-4 last:border-0"><div><div className="font-bold">{t.category}</div><div className="text-xs text-muted-foreground">{t.transaction_date}{t.description?` · ${t.description}`:""}</div></div><div className="flex items-center gap-3"><b className={t.type==="income"?"text-emerald-600":"text-rose-600"}>{t.type==="income"?"+":"-"}{thb(Number(t.amount))}</b>{!t.work_schedule_id&&<button onClick={()=>remove(t.id)} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4"/></button>}</div></div>)}</div>:<div className="rounded-xl border border-dashed border-border p-12 text-center text-muted-foreground">ยังไม่มีรายการเงิน</div>}{open&&<TransactionForm close={()=>setOpen(false)}/>}</div> }
function TransactionForm({close}:{close:()=>void}) { const {user}=useAuth();const qc=useQueryClient();const [type,setType]=useState<"income"|"expense">("expense");const [amount,setAmount]=useState("");const [category,setCategory]=useState("");const [description,setDescription]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [error,setError]=useState("");const save=async(e:React.FormEvent)=>{e.preventDefault();if(!category||!date||Number(amount)<=0){setError("กรอกประเภท หมวดหมู่ วันที่ และจำนวนเงินที่มากกว่า 0");return}const {error}=await supabase.from("transactions" as any).insert({student_id:user!.id,type,amount:Number(amount),category,description:description||null,transaction_date:date,source:"manual"});if(error){setError("บันทึกไม่สำเร็จ กรุณาลองใหม่");return}await qc.invalidateQueries({queryKey:["transactions",user?.id]});await qc.invalidateQueries({queryKey:["money",user?.id]});close()};const cats=type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES;return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={save} className="w-full max-w-md space-y-3 rounded-xl bg-background p-6"><h2 className="font-display text-xl font-bold">เพิ่มรายการเงิน</h2><select value={type} onChange={e=>{setType(e.target.value as any);setCategory("")}} className="w-full rounded border p-2"><option value="expense">รายจ่าย</option><option value="income">รายรับ</option></select><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="จำนวนเงิน" className="w-full rounded border p-2"/><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full rounded border p-2"><option value="">เลือกหมวดหมู่</option>{cats.map(x=><option key={x}>{x}</option>)}</select><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="รายละเอียด" className="w-full rounded border p-2"/><input value={date} onChange={e=>setDate(e.target.value)} type="date" className="w-full rounded border p-2"/>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded border px-3 py-2">ยกเลิก</button><button className="rounded bg-primary px-3 py-2 font-bold text-primary-foreground">บันทึก</button></div></form></div>}
